name: Deploy to AWS (Tomcat)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2
        with:
          path: TestCours 

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build et package de l'application Spring Boot
        run: |
          cd TestCours
          chmod +x mvnw
          ./mvnw clean package
        env:
          MAVEN_OPTS: '-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository'

      - name: Copy files via SSH to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          source: "TestCours/target/demo-0.0.1-SNAPSHOT.war"
          target: "/path/to/tomcat/webapps"
